-- ============================================================
-- Add rich descriptions to protocols
-- ============================================================

UPDATE protocols SET description = 'The Recovery Protocol is built around the Wolverine Blend, which combines BPC-157 and TB-500 in a single vial. BPC-157 is one of the most studied peptides for soft tissue repair, with research showing accelerated healing of tendons, ligaments, and muscle tissue. TB-500 complements it by promoting flexibility, reducing inflammation, and supporting the body''s natural repair processes. Together they form a complete recovery stack used widely in research settings. This is our most popular protocol for a reason. Whether you are recovering from training, dealing with joint discomfort, or looking to support overall tissue health, the Recovery Protocol provides everything you need in one monthly shipment.'
WHERE slug = 'recovery';

UPDATE protocols SET description = 'The Fat Loss Protocol combines three targeted peptides for metabolic support and body recomposition. MOTS-C is a mitochondrial peptide that has been shown in research to activate AMPK pathways, improve metabolic flexibility, and enhance exercise capacity. AOD 9604 is a modified fragment of human growth hormone that specifically targets fat metabolism without affecting blood sugar or growth. The CJC-1295/Ipamorelin Blend provides sustained growth hormone release to support lean tissue preservation while your body mobilizes stored fat. This protocol is designed for researchers focused on body composition. It pairs well with consistent training and a structured nutrition plan for best results.'
WHERE slug = 'fat-loss';

UPDATE protocols SET description = 'The Performance Protocol is designed around growth hormone optimization. The CJC-1295/Ipamorelin Blend provides a sustained, pulsatile release of growth hormone by combining a GHRH analog with a selective ghrelin receptor agonist. This means elevated GH levels without the cortisol or prolactin spikes associated with other secretagogues. The standalone Ipamorelin vial allows for additional dosing flexibility throughout the cycle. Research has linked optimized growth hormone levels to improved recovery between training sessions, better sleep quality, and support for lean muscle tissue. This protocol is a strong fit for researchers focused on strength, endurance, and long-term performance.'
WHERE slug = 'performance';

UPDATE protocols SET description = 'The Full Recomp Protocol is our most comprehensive stack. It combines the recovery benefits of BPC-157 and TB-500 with the growth hormone optimization of CJC-1295/Ipamorelin and the metabolic support of MOTS-C. BPC-157 and TB-500 handle tissue repair and joint health. CJC-1295/Ipamorelin drives sustained growth hormone release for recovery and lean mass support. MOTS-C activates metabolic pathways for improved energy utilization and body composition. This is the protocol for researchers who want to address recovery, performance, and body composition simultaneously. It covers every major goal category in a single monthly shipment with built-in subscription savings.'
WHERE slug = 'full-recomp';
